### PR TITLE
fix: <temp fix> display node address, View document while minting

### LINKED ISSUE #515: Gateway NFT minting flow quick fixes
1) While the NFT is being minted and NFT status is `Minting`, user should be able to View the document

2) MVP For Document view, While NFT is being minted the `Mint NFT` button/link should be deactivated/not displayed and in the NFT table we should show `The NFT is currently being minted. Please find the pending transaction [here](link to Cent Node or link to CF ID].

Later: Once the Node returns the tx status, the link would lead to the pending tx

### PR DESCRIPTION
**Pull request by charleenfei**
Allows Viewing of document while `Minting`

also exposes node address in kovan/mainnet etherscan, depending on ETH_NETWORK

Screenshot 2020-10-30 at 11 26 31

Closes #515

### CODE REVIEW

File: packages/server/src/users/users.controller.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export class UsersController {
 
     try {
       await this.mailerService.sendMail({
-        to: user.email, //user.email,
+        to: user.email,
```
Comment (rdinicut) [inline packages/server/src/users/users.controller.ts:57]: Thanks for this

File: packages/ui/src/documents/ListDocuments.tsx [hunk 2]
```diff
@@ -112,8 +112,8 @@ export const ListDocuments: FunctionComponent<Props> = (props: Props) => {
     return false
   };
 
-  const displayView = (doc_status: string, nft_status: string) => {
-    return nft_status !==  NftStatus.Minting && doc_status !== DocumentStatus.CreationFail;
+  const displayView = (doc_status: string) => {
+    return doc_status !== DocumentStatus.CreationFail;
```
Comment (rdinicut) [inline packages/ui/src/documents/ListDocuments.tsx:116]: I think we can view the document even on fail. We just return what we have in the database in case the document get fails from the node.  Not for this pr...just an idea for the future so you do not have to re-enter the doc and we can add a retry button or something @denniswell

File: packages/ui/src/documents/Nfts.tsx [hunk 3]
```diff
@@ -114,6 +114,12 @@ export const Nfts: FunctionComponent<Props> = (props) => {
     return actions
   };
 
+  const renderNodeUrl = () => {
+    return window['__ETH_NETWORK__'] === 'kovan' ?
+        <a href={"https://kovan.etherscan.io/address/0x44a0579754D6c94e7bB2c26bFA7394311Cc50Ccb"}>here.</a> :
```
Comment (rdinicut) [inline packages/ui/src/documents/Nfts.tsx]: How about adding a new env variable / window constant for the __NODE_ADDRESS__(name can be better)
```
getEthScanNodeUrl = () => {
  return `https://${window.__ETH_NETWORK__=== mainnet ? '': window.__ETH_NETWORK__ }etherscan.io/address/window.___NODE_ADDRESS__`
}
```
Also I will not return the `<a>` but just the url as we can use that in a context where it is not in a link. Maybe it can be a on click trigger

Comment (rdinicut) [reply packages/ui/src/documents/Nfts.tsx]: Maybe we can also use some of this functions 
https://github.com/centrifuge/gateway/blob/5950fc6b239f5f4dba75a341980bfc1860817588/packages/lib/src/utils/etherscan.ts#L23

Comment (charleenfei) [reply packages/ui/src/documents/Nfts.tsx]: i would not set the env variable for now bc this is not intended to stay as is, only until we get the tx hashes from the node job id (this is planned to be specced out next week). will update to use getAddressLink 👍

File: packages/ui/src/documents/ListDocuments.tsx (hunk 2 above)
Comment (charleenfei) [reply packages/ui/src/documents/ListDocuments.tsx:116]: can you open a ticket for this? we can keep it in the backlog but then it will be tracked.

Comment (rdinicut) [reply packages/ui/src/documents/ListDocuments.tsx:116]: #531

**Review by rdinicut — APPROVED** [review]
LGTM
