### PR TITLE
fix  tests

### LINKED ISSUE #494: Investigate/Fix broken/commented server tests

### PR DESCRIPTION
**Pull request by rdinicut**
We should at some point update the fields to be camelCase instead of snake case. The only issue right now is the agreement_id but it is kindOf error prone. Why did we switch to camelCase btw? We were generating snake case from swagger hub using the code gen options?

### CODE REVIEW

**Comment by charleenfei** [comment]
> We should at some point update the fields to be camelCase instead of snake case. The only issue right now is the agreement_id but it is kindOf error prone. Why did we switch to camelCase btw? We were generating snake case from swagger hub using the code gen options?

i couldn't get snake case generation functioning properly with swagger code-gen in a timeboxed way, there is an open issue on this #442. the node expects snake_cased attributes.

**Comment by rdinicut** [comment]
@charleenfei can I merge this?

**Comment by charleenfei** [comment]
I think we should keep it snake_cased and use ts-ignore instead, like how we treat all the other cases in the other controllers, so it is consistent. rn we don't use funding agreements in gw but if we did use them we would need to snake case, so I think we should at least keep it functional.

**Comment by rdinicut** [comment]
so the main problem is here https://github.com/centrifuge/gateway/blob/c88be51afea54ab9d93464a0fdc7818b312942b7/packages/server/src/funding/funding.controller.ts#L65
.
 So the request will return snake case and this is a bug?

**Comment by rdinicut** [comment]
@charleenfei @mikiquantum can you add me to swagger hub https://app.swaggerhub.com/apis/centrifuge.io/cent-node/2.0.0 so I can see the generation options?

**Comment by rdinicut** [comment]
cc @charleenfei I updated the api with snake case and removed all ts-ignores and refactor back to snake case. Can you pull this branch delete all node modules using something like  ``` find . -name "node_modules" -type d -prune -exec rm -rf '{}' +```, yarn install and yarn start?

File: packages/ui/src/documents/CreateDocument.tsx [hunk 1]
```diff
@@ -83,13 +83,14 @@ export const CreateDocument: FunctionComponent<Props> = (props) => {
...
       try {
+
         push(documentRoutes.index);
-        go(0);
         if (document.template && document.template !== '') {
           await httpClient.documents.clone(document);
         } else {
           await httpClient.documents.create(document);
         }
+        go(0);
```
Comment (rdinicut) [inline packages/ui/src/documents/CreateDocument.tsx:93]: I think this was the problem with the proxy error. Also we were not getting the alerts from the document errors. We can improve this for sure but I think it is a different topic

File: packages/ui/src/documents/CreateDocument.tsx [hunk 2]
```diff
@@ -119,7 +120,7 @@ export const CreateDocument: FunctionComponent<Props> = (props) => {
       renderHeader={() => {
         return <SecondaryHeader>
           <Box direction="row" gap="small" align="center">
-            <Link to={documentRoutes.index} size="large">
+            <Link to={documentRoutes.index}>
```
Comment (rdinicut) [inline packages/ui/src/documents/CreateDocument.tsx:123]: Bug, This was generating typescript errors for because Link that not have that prop

File: packages/server/src/centrifuge-client/centrifuge.module.ts [hunk 3]
```diff
@@ -8,10 +8,6 @@ function checkNodeEnvironment() {
     case 'test': {
       return new MockCentrifugeService();
     }
-    case 'functional': {
```
Comment (rdinicut) [inline packages/server/src/centrifuge-client/centrifuge.module.ts:11]: This was also generating typescript error. I assumed we are not using this so I removed it. If we want to add e2e test we can figure it out then

**Review by charleenfei — APPROVED** [review]
